### ISSUE TITLE
The specified container does not exist

### ISSUE THREAD

**Issue by spinal501** [deviceinsight/azure-blob-upload-maven-plugin#1]
Hello,

I use your plugin to upload the contents of directory to an azure storage account and i get the following error : 

[error] org.apache.maven.plugin.MojoExecutionException: The specified container does not exist.
	at com.deviceinsight.azureblobupload.UploadMojo.sendFileToCloud(UploadMojo.java:87)
	at com.deviceinsight.azureblobupload.UploadMojo.execute(UploadMojo.java:50)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: com.microsoft.azure.storage.StorageException: The specified container does not exist.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:877)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:712)
	at com.microsoft.azure.storage.blob.CloudBlob.uploadFromFile(CloudBlob.java:1726)
	at com.microsoft.azure.storage.blob.CloudBlob.uploadFromFile(CloudBlob.java:1698)
	at com.deviceinsight.azureblobupload.UploadMojo.sendFileToCloud(UploadMojo.java:84)

here is my config in pom.xml

			<plugin>
				<groupId>com.deviceinsight.azure</groupId>
				<artifactId>azure-blob-upload-maven-plugin</artifactId>
				<version>1.1.0</version>
				<executions>
					<execution>
						<id>upload</id>
						<phase>deploy</phase>
						<goals>
							<goal>upload</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<connectionString>DefaultEndpointsProtocol=https;AccountName=*****=******;EndpointSuffix=****</connectionString>
					<rootDir>${project.build.directory}/upload</rootDir>
				</configuration>
			</plugin>

Can you help me plz.

Best regards,
--
Khaled

**Comment by stefan-hudelmaier** [comment]
Hi, 

the containerName was statically set to "$web" because we only use this plugin for uploading content for static websites hosted on Storage Containers. We have released version 2.0.0 of this plugin that makes it possible to add the `containerName` to the `configuration` tag. I hope this will fix your issue. If not, please re-open this ticket.

Kind regards,
Stefan
